server:
  port: 8081
spring:
  application:
    name: account-service #指定服务名称
  datasource:
    username: root
    password: sixinbuxi
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://zrylovestan.com:3306/microservices?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false #可考虑加一个查询参数
#  datasource:
#    hikari:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#      jdbc-url: jdbc:mysql://192.168.1.13:3306/microservices #可考虑加一个查询参数
#      username: root
#      password: alan
mybatis: #mybatis
  type-aliases-package: com.alan.microservices.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mybatis/mapper/*.xml


eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.16:8761/eureka/
  instance:
    prefer-ip-address: true #将本机ip注册到eureka server,而不是hostname

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'