server:
  port: 8081
spring:
  application:
    name: account-service #指定服务名称
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #将本机ip注册到eureka server,而不是hostname

    #  datasource:
    #      jdbc-url: jdbc:mysql://alannnn.tpddns.cn:3306/lab
    #      username: root
    #      password: alan
    #      driver-class-name: com.mysql.cj.jdbc.Driver
    #mybatis:
    #  config-location: classpath:mybatis/mybatis-config.xml
    #  mapper-locations: classpath:mybatis/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans