server:
  port: 80
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.22:30001/eureka/


# ========添加配置=======
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*" #注意这里*要加引号，暴露全部，也可以只暴露相应endpoint
#  endpoint:
#    routes:
#      enabled: true # 默认为true，可以省略
zuul:
  routes:
    account-service: /account/**
    asset-service: /asset/**
    event-service: /event/**
