server:
  port: 8084
spring:
  application:
    name: event-service #指定服务名称
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.16:30001/eureka/
  instance:
    prefer-ip-address: true #将本机ip注册到eureka server,而不是hostname

mqtt:
  brokerUrl: tcp://zrylovestan.com:1883
  clientId: springboot
  cleanSession: false
  pipelines:
    - mqttTopic: /site/data
      kafkaTopic: site-data
      consumerCnt: 3
    - mqttTopic: /site/status/#
      kafkaTopic: site-status
      consumerCnt: 1

status:
  kafkaTopic: site-status
  partitions: 3

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false


ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

logging:
  level:
    com.alan.microservices.event.handler.Producer: info
    com.alan.microservices.event.handler.etl.DevStatusHandler: info
    com.alan.microservices.event.handler.service.mqtt.Producer: info
    com.alan.microservices.event.handler.DeviceOnlineService: info
#  config: classpath:test-logback.xml