mqtt:
  brokerUrl: tcp://192.168.1.13:1883
  clientId: springboot
  pipelines:
    - mqttTopic: /site/data
      kafkaTopic: site-data
      consumerCnt: 2
    - mqttTopic: /site/status
      kafkaTopic: site-status
      consumerCnt: 1