mqtt:
  brokerUrl: tcp://192.168.1.13:1883
  clientId: springboot
  cleanSession: false
  pipelines:
    - mqttTopic: /site/data
      kafkaTopic: site-data
      consumerCnt: 3
    - mqttTopic: /site/status/#
      kafkaTopic: site-status
      consumerCnt: 1

logging:
  level:
    com.alan.microservices.event.handler.Producer: debug
