server:
  port: 8080
spring:
  application:
    name: auth-service #指定服务名称
  datasource:
    username: root
    password: sixinbuxi
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://zrylovestan.com:3306/microservices?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false #可考虑加一个查询参数
#    hikari:
#      max-lifetime: 30000
mybatis: #mybatis
#  type-aliases-package: com.alan.microservices.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #将本机ip注册到eureka server,而不是hostname

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'