server:
  port: 8080
spring:
  application:
    name: asset-service #指定服务名称
  datasource:
    username: root
    password: sixinbuxi
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://zrylovestan.com:3306/microservices?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false #可考虑加一个查询参数